version: '2'
services:
    symfony:
        build: ./docker/symfony
        volumes:
            - /var/www/it-resume
            - ./symfony/:/var/www/it-resume
    nginx:
        image: nginx:1.13.0-alpine
        volumes:
#            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/it:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - 8080:80
        volumes_from:
          - drupal
          - symfony
    drupal:
        build: ./docker/drupal
        volumes:
            - /var/www/html
            - ./drupal/:/var/www/html
    db:
        image: mysql:5
        ports:
            - 3306:3306
        volumes:
            - ./docker/db/dump:/dump
        environment:
            MYSQL_DATABASE: drupal
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
